_import: configs/train_base_ar_float.yaml

boat:

  models:
    net:
      path: 'rhautoregression.nn.model_zoo.pixelcnnpp'
      name: 'PixelCNNPlusPlus'
      params:
        kernel_size: $kernel_size
        in_channels: $in_channels
        hidden_channels: $hidden_channels
        n_blocks: $n_blocks
        nr_mix: $nr_mix

_vars:

  kernel_size: 3
  in_channels: 3
  hidden_channels: 256
  n_blocks: 8
  nr_mix: 10

  devices: [0, 1]

  train_batch_size: 64
  valid_batch_size: 8
  num_workers: 16

  max_epochs: 200

  train_folder_paths:
    gt: data/ffhq/ffhq_imgs/ffhq_64
    
  valid_folder_paths:
    gt: data/celeba/subsets/celeba_64

  experiment_name: pixelcnnpp_ffhq_64

  ema_start: 0