_import: configs/train_base_ar_discrete.yaml

_vars:

  net:
    path: 'rhautoregression.nn.model_zoo.pixelcnn'
    name: 'PixelCNN'
    params:
      vocab_size: 256
      kernel_size: 9
      in_channels: 3
      hidden_channels: 384

  devices: [0, 1]

  train_batch_size: 64
  valid_batch_size: 8
  num_workers: 16

  train_folder_paths:
    gt: data/ffhq/ffhq_imgs/ffhq_64
    
  valid_folder_paths:
    gt: data/celeba/subsets/celeba_64

  experiment_name: pixelcnn_ffhq_64

  ema_start: 3000